# SPDX-License-Identifier: Apache-2.0
function(bes2700yp_import_hal root lock)
  file(SHA256 "${root}/manifest.json" actual)
  file(READ "${lock}" expected)
  string(STRIP "${expected}" expected)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "HAL manifest.json SHA256 differs from hal-release.sha256")
  endif()
  file(READ "${root}/manifest.json" metadata)
  foreach(field chip profile abi)
    string(JSON ${field} GET "${metadata}" ${field})
  endforeach()
  if(NOT chip STREQUAL "bes2700yp" OR NOT profile STREQUAL "dual_v1_24m_t2"
     OR NOT abi STREQUAL "cortex-m33-fpv5-sp-d16-hard")
    message(FATAL_ERROR "Unsupported HAL chip/profile/ABI")
  endif()
  string(JSON count LENGTH "${metadata}" artifacts)
  math(EXPR last "${count} - 1")
  foreach(index RANGE ${last})
    string(JSON name MEMBER "${metadata}" artifacts ${index})
    string(JSON expected GET "${metadata}" artifacts "${name}")
    set(fetch_hint "")
    if(name MATCHES "[.]a$")
      set(fetch_hint "; run west blobs fetch hal_bestechnic from the workspace root")
    endif()
    if(NOT EXISTS "${root}/${name}")
      message(FATAL_ERROR "Missing HAL artifact: ${name}${fetch_hint}")
    endif()
    file(SHA256 "${root}/${name}" actual)
    if(NOT actual STREQUAL expected)
      message(FATAL_ERROR "HAL artifact checksum mismatch: ${name}${fetch_hint}")
    endif()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${root}/${name}")
  endforeach()
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    "${root}/manifest.json" "${root}/zephyr/module.yml" "${lock}")
  foreach(group system flash bootstrap_compat)
    add_library(bes2700yp_${group} STATIC IMPORTED)
    set_target_properties(bes2700yp_${group} PROPERTIES IMPORTED_LOCATION
      "${root}/zephyr/blobs/lib/bes2700yp/${abi}/${profile}/libbes2700yp_${group}.a")
  endforeach()
endfunction()
